<h1>U23AI001 DL Assignment 1</h1>

<h4> Q1. Introduction of PyTorch Tensors and Basic Operations.</h4>
a. To understand PyTorch tensors, their initialization methods, and data types. <br>


In [1]:
import torch
print(torch.__version__)

2.9.1+cpu


Creating tensors

In [2]:
# using empty
a = torch.empty(2,3)
print(a)

# using zeros
b = torch.zeros(2,3)
print(b)

# using ones
c = torch.ones(2,3)
print(c)

# using rand (randomly value between 0 and 1)
d = torch.rand(2,3)
print(d)

# using tensor
e = torch.tensor([[1,2,3],[4,5,6]])
print(e)

tensor([[2.4263e-35, 1.5891e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.9629, 0.3265, 0.8319],
        [0.3763, 0.0091, 0.6239]])
tensor([[1, 2, 3],
        [4, 5, 6]])


<h4>Datatypes</h4>

In [3]:
f = torch.tensor([1.5, 2.5], dtype=torch.float32)
g = torch.tensor([1, 2], dtype=torch.int32)

print(f, f.dtype)
print(g, g.dtype)

tensor([1.5000, 2.5000]) torch.float32
tensor([1, 2], dtype=torch.int32) torch.int32


### b) To perform tensor operations such as arithmetic, broadcasting, indexing, and reshaping.

Arithmetic


In [4]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

print(x + y)
print(x * y)
print(x @ y)

tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[19, 22],
        [43, 50]])


Broadcasting

In [5]:
z = torch.tensor([10, 20])
print(x + z)

tensor([[11, 22],
        [13, 24]])


Indexing

In [6]:
print(x[0, 1])
print(x[:, 0])

tensor(2)
tensor([1, 3])


Reshaping

In [7]:
x = torch.arange(6)
print(x)
y = x.reshape(2, 3)
print(y)

tensor([0, 1, 2, 3, 4, 5])
tensor([[0, 1, 2],
        [3, 4, 5]])


### c) To explore automatic differentiation using PyTorch’s Autograd system.

In [8]:
x = torch.tensor(3.0, requires_grad=True)
y = x**2 + 2*x + 1
y.backward()

print("Gradient:", x.grad)

Gradient: tensor(8.)


<h4> Q2. PERFORM ALL LINEAR ALGEBRA WITH TENSOR FLOW </h4>


In [3]:
import tensorflow as tf

In [2]:
Scalar = tf.constant(5)
print(Scalar) 

tf.Tensor(5, shape=(), dtype=int32)


In [3]:
Vector = tf.constant([6, 3])
print("Vector:", Vector)

Vector: tf.Tensor([6 3], shape=(2,), dtype=int32)


In [6]:
Matrix = tf.constant([[4, 2, 0], [0, 6, 9]])
print("Matrix:", Matrix)
print("Shape:",Matrix.shape)
print("Rank:",tf.rank(Matrix))
print("Size:",tf.size(Matrix))

Matrix: tf.Tensor(
[[4 2 0]
 [0 6 9]], shape=(2, 3), dtype=int32)
Shape: (2, 3)
Rank: tf.Tensor(2, shape=(), dtype=int32)
Size: tf.Tensor(6, shape=(), dtype=int32)


In [7]:
A = tf.constant([[4, 2],
                 [6, 9]])

B = tf.constant([[2, 1],
                 [5, 3]])

print("A + B:", tf.add(A, B))
print("A - B:", tf.subtract(A, B))


A + B: tf.Tensor(
[[ 6  3]
 [11 12]], shape=(2, 2), dtype=int32)
A - B: tf.Tensor(
[[2 1]
 [1 6]], shape=(2, 2), dtype=int32)


In [10]:
scalar_mul = tf.multiply(A, 3)
print("Scalar Multiplication:\n", scalar_mul, "\n")

matmul = tf.matmul(A, B)
print("Matrix Multiplication:\n", matmul)


Scalar Multiplication:
 tf.Tensor(
[[12  6]
 [18 27]], shape=(2, 2), dtype=int32) 

Matrix Multiplication:
 tf.Tensor(
[[18 10]
 [57 33]], shape=(2, 2), dtype=int32)


In [11]:
det = tf.linalg.det(tf.cast(A, tf.float32))
print("Determinant:", det)

Determinant: tf.Tensor(24.0, shape=(), dtype=float32)


In [12]:
vector = tf.constant([6.3, 2.9])

l2_norm = tf.norm(vector, ord=2)
l1_norm = tf.norm(vector, ord=1)

print("L2 Norm:", l2_norm)
print("L1 Norm:", l1_norm)


L2 Norm: tf.Tensor(6.9354167, shape=(), dtype=float32)
L1 Norm: tf.Tensor(9.200001, shape=(), dtype=float32)


In [13]:
A = tf.constant([[2.1, 4.3],
                 [6.5, 8.7]])

B = tf.constant([[10.9],
                 [12.11]])

X = tf.linalg.solve(A, B)
print("Solution X:\n", X)


Solution X:
 tf.Tensor(
[[-4.417044 ]
 [ 4.6920443]], shape=(2, 1), dtype=float32)


In [15]:
A = tf.constant([[1.5, 0.9],
                 [0.1, 1.2]])

power = tf.linalg.matmul(A, A)
print("Matrix Power A^2:\n", power)


Matrix Power A^2:
 tf.Tensor(
[[2.34      2.4299998]
 [0.27      1.5300001]], shape=(2, 2), dtype=float32)


<h4>Q3. Write a program to implement AND & OR gates using Perceptron</h4>

In [18]:


def perceptron_AND(x1, x2):
    w1 = 1
    w2 = 1
    bias = -2
    net = w1*x1 + w2*x2 + bias
    if net >= 0:
        return 1
    else:
        return 0

print("AND Gate")
inputs = [(0,0), (0,1), (1,0), (1,1)]
for x1, x2 in inputs:
    print(f"{x1} AND {x2} = {perceptron_AND(x1, x2)}")

print("\n")

def perceptron_OR(x1, x2):
    w1 = 1
    w2 = 1
    bias = -1
    net = w1*x1 + w2*x2 + bias
    if net >= 0:
        return 1
    else:
        return 0

print("OR Gate")
inputs = [(0,0), (0,1), (1,0), (1,1)]
for x1, x2 in inputs:
    print(f"{x1} OR {x2} = {perceptron_OR(x1, x2)}")

AND Gate
0 AND 0 = 0
0 AND 1 = 0
1 AND 0 = 0
1 AND 1 = 1


OR Gate
0 OR 0 = 0
0 OR 1 = 1
1 OR 0 = 1
1 OR 1 = 1


<h4>Q4. Implementation of XOR Problem using PyTorch Neural Network</h4>

In [20]:
import torch
import torch.nn as nn
import torch.optim as optim


In [21]:

A = torch.tensor([[0., 0.],
                  [0., 1.],
                  [1., 0.],
                  [1., 1.]])

B = torch.tensor([[0.],
                  [1.],
                  [1.],
                  [0.]])


In [22]:
class XORNet(nn.Module):
    def __init__(self):
        super(XORNet, self).__init__()
        self.hidden = nn.Linear(2, 4)  
        self.output = nn.Linear(4, 1)

    def forward(self, x):
        x = torch.relu(self.hidden(x)) 
        x = self.output(x)             
        return x

In [24]:
model = XORNet()

criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

epochs = 5000
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(A)
    loss = criterion(outputs, B)
    loss.backward()
    optimizer.step()


In [26]:
epochs = 10000

for epoch in range(epochs):
    optimizer.zero_grad()
    
    outputs = model(A)
    loss = criterion(outputs, B)
    
    loss.backward()
    optimizer.step()
    
    if (epoch+1) % 1000 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")


Epoch [1000/10000], Loss: 0.3466
Epoch [2000/10000], Loss: 0.3466
Epoch [3000/10000], Loss: 0.3466
Epoch [4000/10000], Loss: 0.3466
Epoch [5000/10000], Loss: 0.3466
Epoch [6000/10000], Loss: 0.3466
Epoch [7000/10000], Loss: 0.3466
Epoch [8000/10000], Loss: 0.3466
Epoch [9000/10000], Loss: 0.3466
Epoch [10000/10000], Loss: 0.3466


In [27]:
with torch.no_grad():
    logits = model(A)
    predictions = torch.sigmoid(logits)
    predictions = (predictions > 0.5).int()
    print(predictions)

tensor([[0],
        [0],
        [1],
        [0]], dtype=torch.int32)


<h4>Q5. Implement Simple below Neural Network to solve regression problem</h4>

In [34]:

A = torch.tensor([[10., 12.],
                  [32., 20.],
                  [3., 9.],
                  [14., 18.]], dtype=torch.float32)

B = torch.tensor([[2.],
                  [9.],
                  [25.],
                  [7.]], dtype=torch.float32)


In [35]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()

        self.hidden = nn.Linear(2, 2)
        

        self.output = nn.Linear(2, 1)
        
    def forward(self, x):
        h = torch.relu(self.hidden(x))   
        y = self.output(h)               
        return y


In [36]:
model = SimpleNN()

criterion = nn.MSELoss()    
optimizer = optim.SGD(model.parameters(), lr=0.01)


In [39]:
epochs = 5000

for epoch in range(epochs):
    optimizer.zero_grad()
    
    predictions = model(A)
    loss = criterion(predictions, B)
    
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % 500 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")


Epoch 500, Loss: 74.1875
Epoch 1000, Loss: 74.1875
Epoch 1500, Loss: 74.1875
Epoch 2000, Loss: 74.1875
Epoch 2500, Loss: 74.1875
Epoch 3000, Loss: 74.1875
Epoch 3500, Loss: 74.1875
Epoch 4000, Loss: 74.1875
Epoch 4500, Loss: 74.1875
Epoch 5000, Loss: 74.1875


In [41]:
with torch.no_grad():
    test_input = torch.tensor([[23., 68.]])
    output = model(test_input)
    print("Predicted output:", output.item())


Predicted output: 10.749977111816406
